### ISSUE TITLE
Read only accounts

### ISSUE THREAD

**Issue by gcottletcc** [detunized/lastpass-ruby#14] opened 2019-11-05 23:54 UTC
The `Vault.open_remote` method only returns accounts that I've created and is not returning my shared Read-Only accounts

**Comment by detunized** [comment] 2019-11-06 10:02
This does library support shared folders. It's possible though that not all the special cases are handled correctly. At the moment I don't the time to investigate this. If you are willing to figure this out and submit a PR, you're more than welcome and it would be highly appreciated. Thanks.

**Comment by detunized** [comment] 2020-05-17 11:14
@gcottletcc do you have any details on this. How do I reproduce this?

**Comment by detunized** [comment] 2023-02-20 11:37
The issue is too old. No followup. Closing.

**Closed by detunized** 2023-02-20 11:37 UTC
