### ISSUE TITLE
bad decrypt error when opening vault.

### ISSUE THREAD

**Issue by mikeslattery** [detunized/lastpass-ruby#9] opened 2015-07-07 18:38 UTC
```
vault = LastPass::Vault.open_remote uername, password, secondfactor
```

Causes:

```
OpenSSL::Cipher::CipherError: bad decrypt
    lib/lastpass/parser.rb:282:in `final'
    lib/lastpass/parser.rb:282:in `decode_aes256'
    lib/lastpass/parser.rb:249:in `decode_aes256_cbc_plain'
    lib/lastpass/parser.rb:206:in `decode_aes256_plain_auto'
    lib/lastpass/parser.rb:44:in `block in parse_ACCT'
    lib/lastpass/parser.rb:37:in `open'
    lib/lastpass/parser.rb:37:in `parse_ACCT'
    lib/lastpass/vault.rb:58:in `block in parse_accounts'
    lib/lastpass/vault.rb:54:in `each'
    lib/lastpass/vault.rb:54:in `parse_accounts'
    lib/lastpass/vault.rb:41:in `initialize'
    lib/lastpass/vault.rb:22:in `new'
    lib/lastpass/vault.rb:22:in `open'
    lib/lastpass/vault.rb:11:in `open_remote'
```

However, the [lastpass-cli](https://github.com/LastPass/lastpass-cli) utility works fine.

**Comment by detunized** [comment] 2015-08-04 17:58
Sorry for delayed response. I was on vacation. Does this error reproduce every time? Are you willing to put some effort into tracking this down with my help? I cannot just reproduce this with my account and I won't be asking for your credentials obviously. If you're interested I'd take it private (detunized@gmail.com) and give you some hints what would be nice to dump. Thanks for reporting this BTW.

**Comment by mikeslattery** [comment] 2015-08-05 02:34
Yes, every time.  I'm running on xubuntu 14.04 and Ruby 1.9.3.  It appears that authentication is successful, including a 2nd factor.  You want me to try on Windows and/or a different version of Ruby?

I can put some time in this weekend.  I'll email you.

**Comment by mikeslattery** [comment] 2015-09-18 18:05
This only happens when using 2nd factor as the 3rd argument.   I'm using the Google Authenticator Android app.  I'm providing the code it displays as the 3rd argument to open_remote().  I expect that if you used Google Authenticator you would experience the same symptoms.

**Comment by detunized** [comment] 2015-09-20 10:00
Could you try to disable GAuth on this account and try to log in without it? I'm pretty sure it has nothing to do with that, unless the "one time password" code is incorrect. GAuth in no way changes the data that is received from the LP server. I'm using it with GAuth enabled on my account and everything works fine.

Do you have any shared folders in this account?

**Comment by CGamesPlay** [comment] 2016-02-16 19:05
I'm encountering this issue and am using shared folders on this account. The gem used to work fine but broke within the past few weeks. I'm not sure if anything changed in the LastPass account that would trigger this, but that seems likely. Not sure what it would be.

I have the error in the same place.

**Comment by detunized** [comment] 2016-02-17 11:03
@CGamesPlay, I will look into that. I'll try to match my code against their JS. The problem is that I cannot reproduce this on my accounts so I don't really know how to debug this. It's obviously sensitive data, so I cannot go around ask people for their passwords. I see what I can do. Are you willing to try to run an instrumented with debug prints local build of this gem? Maybe we can track it down together.

**Comment by CGamesPlay** [comment] 2016-02-20 21:22
Yeah I can run a customized version to help track this down.

**Comment by CGamesPlay** [comment] 2016-11-03 00:31
I didn't do a ton of debugging to be sure, but I did notice that a deleting a record with a blank user name and blank password fixed the error on my particular vault. I just added `puts name` at parser.rb line 44 to help debug.

**Comment by detunized** [comment] 2017-02-05 16:02
I tested with the blank username, password and everything else. I don't see any problems. Is it still reproducible on your end? I just discovered this issue open for quite some time, I didn't get any notifications about it. Weird.

**Comment by CGamesPlay** [comment] 2017-02-05 18:07
Sorry, I probably should have saved the bad version but I did not. I'll take a closer look if we notice this starts happening again.

**Comment by detunized** [comment] 2018-04-17 20:51
Is this still reproducible? I'll close the ticket otherwise.

**Comment by detunized** [comment] 2018-04-23 12:13
I'm closing as it's very old. If you see this again, please reopen.

**Closed by detunized** 2018-04-23 12:13 UTC
